name: Build Native Binaries for macOS

on:
  workflow_dispatch: # Trigger manually from Actions tab
  push:
    tags:
      - "v*" # OR when you push a version tag like `v1.0.0`

jobs:
  build:
    name: Build macOS ${{ matrix.arch }}
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64] # You can add more like arm64 if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install build dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install python3

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Package native binary
        run: npm run package

      - name: Upload to GitHub Release
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Publishing to GitHub Release..."
          npx node-pre-gyp-github publish --release
