name: Build Windows arm64 Binaries

on:
  release:
    types: [created]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }} (Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-11-arm]
        arch: [arm64]
        node-version: [19, 20, 21, 22, 23, 24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build
        run: |
          npm ci --ignore-scripts

      - name: Install node-gyp globally
        run: npm install -g node-gyp

      - name: Build native addon and copy to lib
        run: |
          node-gyp clean
          node-gyp configure
          node-gyp build
          node ./copy.js

      - name: Package native binary
        run: npm run package
