name: Build Windows arm64 Binaries

on:
  workflow_dispatch: # Trigger manually from Actions tab
  push:
    tags:
      - "v*" # OR when you push a version tag like `v1.0.0`

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }} (Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-11-arm]
        arch: [arm64]
        node-version: [18, 19, 20, 21, 22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build
        run: |
          npm install
          npm install --global windows-build-tools
          npm run build

      - name: Package native binary
        run: npm run package

      - name: Upload to GitHub Release
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Publishing to GitHub Release..."
          npx node-pre-gyp-github publish --release
