name: Build Native Binaries for linux arm64

on:
  release:
    types: [created]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }} ${{ matrix.arch }} Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm]
        arch: [arm64]
        node-version: [18, 19, 20, 21, 22, 23, 24]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}

      - name: Install build dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Install node-gyp globally
        run: npm install -g node-gyp

      - name: Build native addon and copy to lib
        run: |
          node-gyp clean
          node-gyp configure
          node-gyp build
          node ./copy.js

      - name: Package native binary
        run: npm run package
